#!/bin/sh
#export LD_LIBRARY_PATH=/usr/lib/oracle/12c/client64/lib
sqlplus64 "dmielnik/11128927@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle12c.scs.ryerson.ca)(Port=1521))(CONNECT_DATA=(SID=orcl12c)))" <<EOF

-- Display All for Each
SELECT * FROM Customers;

SELECT * FROM Sellers;

SELECT * FROM Products;

SELECT * FROM Inventory;

SELECT * FROM Order_History;

-- Views
-- Sellers | Poorly rated sellers who have been suspended
SELECT * FROM poorly_rated_suspended_sellers;

-- Products + Order_History | Numbeer of times a product has been orderd from specified seller
SELECT * FROM product_order_totals;

-- Order_History | Total in shipment to each loaction
SELECT * FROM location_shipped_totals;

-- Inventory + Products | Next product delivery date for specified seller;
SELECT * FROM next_prod_delivery;

-- Inventory + Sellers | Get all inventory items that are below the minimum stock threshold
SELECT * FROM needs_restocking;

-- Queries
-- Customers + Order_History | Total orders by customer, what customers order the most
SELECT c.customer_id, c.customer_name, COUNT(o.transaction_id) AS total_orders
FROM Customers c
JOIN Order_History o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_orders DESC;

-- Products + Inventory | Gets products with less than 20 in stock
SELECT p.product_id, p.product_name, i.in_stock
FROM Products p
JOIN Inventory i ON p.product_id = i.product_id
WHERE i.in_stock < 20
ORDER BY i.in_stock ASC;

-- Order_History + Products | Understand top products by month
SELECT EXTRACT(MONTH FROM o.order_date) AS month, p.product_name, COUNT(o.product_id) AS total_sold
FROM Order_History o
JOIN Products p ON o.product_id = p.product_id
GROUP BY EXTRACT(MONTH FROM o.order_date), p.product_name
ORDER BY month ASC, total_sold DESC;

-- Customers | Display all users whose roll is customer
SELECT customer_id, customer_name, email
FROM Customers
WHERE user_role = 'Customer';

-- Sellers | Display all users whose rating is greater than 4 and status is active
SELECT seller_id, seller_name, email
FROM Sellers
WHERE rating >= 4
AND account_status = 'Active';

-- Products | Display all products with a rating greater than 4 in ascending order
SELECT product_id, product_name, product_price
FROM Products
WHERE rating >= 4
ORDER BY product_price ASC;

-- Inventory + Products | Display combined inventory and products table with specified data where based on the product delivery date
SELECT p.seller_id, i.product_id, p.product_name, i.next_delivery_date, i.next_shipment_quantity
FROM Inventory i
JOIN Products p ON i.product_id = p.product_id
WHERE i.next_delivery_date BETWEEN SYSDATE AND SYSDATE + 20;

-- Order_History + Products + Customers | Display customer and seller names connected to transaction number
SELECT o.transaction_id, p.product_name, c.customer_name
FROM Order_History o
JOIN Products p ON o.product_id = p.product_id
JOIN Customers c ON o.customer_id = c.customer_id
WHERE o.status = 'Pending'
ORDER BY o.order_date ASC;

-- Product + Order_History | Display frst five rows of product name and order total connected through product id
SELECT *
FROM (
    SELECT p.product_id, p.product_name, SUM(o.order_total) AS OrderTotal
    FROM Products p
    JOIN Order_History o ON p.product_id = o.product_id
    GROUP BY p.product_id, p.product_name
    ORDER BY OrderTotal DESC
)
WHERE ROWNUM <= 5;

-- Sellers + Products + Order_History | Display total orders pending for seller
SELECT o.product_id, COUNT(o.product_id) AS total_pending
FROM Order_History o
JOIN Products p ON o.product_id = p.product_id
WHERE o.status = 'Pending'
AND p.seller_id = '75849473'
GROUP BY o.product_id
ORDER BY total_pending DESC;

-- Out of Stock Products with Seller Names | Lists all products that are currently out of stock, along with the names of their sellers.
SELECT p.product_id, p.product_name, s.seller_name, i.in_stock
FROM Products p
JOIN Sellers s ON p.seller_id = s.seller_id
JOIN Inventory i ON p.product_id = i.product_id
WHERE i.in_stock = 0;

-- Top 3 Most Ordered Products
SELECT p.product_id, p.product_name, COUNT(o.transaction_id) AS total_orders
FROM Products p
JOIN Order_History o ON p.product_id = o.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_orders DESC
FETCH FIRST 3 ROWS ONLY;

-- Total Revenue per Seller | Calculates the total revenue generated by each seller from their sold products.
SELECT s.seller_id, s.seller_name, SUM(o.order_total) AS total_revenue
FROM Sellers s
JOIN Products p ON s.seller_id = p.seller_id
JOIN Order_History o ON p.product_id = o.product_id
GROUP BY s.seller_id, s.seller_name
ORDER BY total_revenue DESC;

-- Products Never Ordered | Finds products that have never been ordered by any customer.
SELECT p.product_id, p.product_name, s.seller_name
FROM Products p
JOIN Sellers s ON p.seller_id = s.seller_id
LEFT JOIN Order_History o ON p.product_id = o.product_id
WHERE o.product_id IS NULL
ORDER BY p.product_id;

-- Average Age of Customers by User Role | Computes the average age of customers, grouped by their user role (e.g., 'Customer', 'Admin').
SELECT c.user_role, AVG(TRUNC(MONTHS_BETWEEN(SYSDATE, c.date_of_birth) / 12, 1)) AS avg_age
FROM Customers c
GROUP BY c.user_role
ORDER BY c.user_role;

exit;
EOF
